achtung nicht fertig:
realrshw/Projekt pull request #27
Opened 2022-11-14 09:31 UTC by Bommberk

login+register

Signed-off-by: Bommberk <83213983+Bommberk@users.noreply.github.com>

2022-11-14 09:32 UTC, JDLPIXEL reviewed
Unfertig

2022-11-16 07:02 UTC, JDLPIXEL commented
gzjtz

2022-11-16 07:19 UTC, Merlin0006 requested changes
Muss geändert werden

2022-11-16 07:19 UTC, Merlin0006 commented on functions.php
> +        $user = $_REQUEST["username"];
Email fehlt

2022-11-16 07:19 UTC, Merlin0006 commented on index.php
> +<html lang="en">
De statt En

2022-11-16 07:19 UTC, Merlin0006 commented on index.php
> +    <title>Document</title>
Ordentlicher Titel

2022-11-16 07:19 UTC, Merlin0006 commented on functions.php
> +            $datei = fopen("userdata/$user.txt", "r");
Nicht Richtiger PFad
#

2022-11-16 07:20 UTC, Merlin0006 commented on functions.php
> +        $passwort = $_REQUEST["password"];
Geburtstag

2022-11-16 07:20 UTC, Merlin0006 commented on functions.php
> +        $datei = fopen("userdata/$user.txt","w+");
Falscher Pfad

2022-11-16 07:20 UTC, Merlin0006 commented on functions.php
> +        header("location: https://google.com");
Falsche domain

2022-11-16 07:21 UTC, Merlin0006 commented on index.php
> +    <link rel="stylesheet" href="style.css">
Nicht richtiger Pfad

2022-11-16 07:21 UTC, Merlin0006 commented on index.php
> +                <form action="" method="POST">
Email input fehlt

2022-11-16 07:21 UTC, Merlin0006 commented on index.php
> +                    <input placeholder="Benutzername" type="text" name="username" id=""><br>
Geburstagum input fehlt

2022-11-17 07:47 UTC, closed without merging